
app:
  name: My First App
  home: /

  include: database.yml

  page:
    home: People
    team: Team

  entity:
    People:
      name: string
      surname: string
      age: int
    Team:
      name: string
      league: string
      people: People*
